"""JMessage TUI themes."""

THEMES = {
    "midnight": {
        "label": "Midnight",
        "desc": "Pure black, vibrant colors",
        "bg": "#000000",
        "header_bg": "#111111",
        "highlight_bg": "#1a1a1a",
        "you_color": "#00e676",
        "imessage_color": "#42a5f5",
        "sms_color": "#4caf50",
        "text_color": "#ffffff",
        "timestamp_color": "#666666",
        "separator_color": "#666666",
        "accent": "#00e676",
        "name_color": "#40c4ff",
        "badge_color": "#e040fb",
        "sms_tag_color": "#ff9800",
        "hint_color": "#666666",
        "dim_color": "#555555",
    },
    "console": {
        "label": "Console",
        "desc": "Ops-center dark theme",
        "bg": "#1a1d21",
        "header_bg": "#14181c",
        "highlight_bg": "#22262b",
        "you_color": "#3fb950",
        "imessage_color": "#58a6ff",
        "sms_color": "#3fb950",
        "text_color": "#e1e4e8",
        "timestamp_color": "#6e7681",
        "separator_color": "#6e7681",
        "accent": "#3fb950",
        "name_color": "#58a6ff",
        "badge_color": "#f0883e",
        "sms_tag_color": "#f0883e",
        "hint_color": "#6e7681",
        "dim_color": "#8b949e",
    },
    "ocean": {
        "label": "Ocean",
        "desc": "Deep blue, cool tones",
        "bg": "#0a0e17",
        "header_bg": "#0f1923",
        "highlight_bg": "#142033",
        "you_color": "#64ffda",
        "imessage_color": "#82b1ff",
        "sms_color": "#69f0ae",
        "text_color": "#cfd8dc",
        "timestamp_color": "#546e7a",
        "separator_color": "#546e7a",
        "accent": "#64ffda",
        "name_color": "#82b1ff",
        "badge_color": "#ff8a80",
        "sms_tag_color": "#69f0ae",
        "hint_color": "#546e7a",
        "dim_color": "#607d8b",
    },
    "ember": {
        "label": "Ember",
        "desc": "Warm darks, fire accents",
        "bg": "#1a1210",
        "header_bg": "#241a16",
        "highlight_bg": "#2e2018",
        "you_color": "#ffab40",
        "imessage_color": "#ef5350",
        "sms_color": "#66bb6a",
        "text_color": "#efebe9",
        "timestamp_color": "#795548",
        "separator_color": "#795548",
        "accent": "#ffab40",
        "name_color": "#ff8a65",
        "badge_color": "#ff5252",
        "sms_tag_color": "#66bb6a",
        "hint_color": "#795548",
        "dim_color": "#8d6e63",
    },
    "vapor": {
        "label": "Vapor",
        "desc": "Neon pink and purple",
        "bg": "#0d0221",
        "header_bg": "#150535",
        "highlight_bg": "#1a0a3e",
        "you_color": "#ff6ec7",
        "imessage_color": "#7c4dff",
        "sms_color": "#00e5ff",
        "text_color": "#e0d0ff",
        "timestamp_color": "#6a4c93",
        "separator_color": "#6a4c93",
        "accent": "#ff6ec7",
        "name_color": "#b388ff",
        "badge_color": "#ff4081",
        "sms_tag_color": "#00e5ff",
        "hint_color": "#6a4c93",
        "dim_color": "#9575cd",
    },
    "mono": {
        "label": "Mono",
        "desc": "Clean grayscale, no fuss",
        "bg": "#000000",
        "header_bg": "#111111",
        "highlight_bg": "#1a1a1a",
        "you_color": "#ffffff",
        "imessage_color": "#aaaaaa",
        "sms_color": "#aaaaaa",
        "text_color": "#cccccc",
        "timestamp_color": "#555555",
        "separator_color": "#555555",
        "accent": "#ffffff",
        "name_color": "#cccccc",
        "badge_color": "#ffffff",
        "sms_tag_color": "#888888",
        "hint_color": "#555555",
        "dim_color": "#777777",
    },
    "imessage": {
        "label": "iMessage",
        "desc": "Classic Mac Messages look",
        "bg": "#ffffff",
        "header_bg": "#f5f5f5",
        "highlight_bg": "#e8e8e8",
        "you_color": "#0b93f6",
        "imessage_color": "#333333",
        "sms_color": "#4caf50",
        "text_color": "#1a1a1a",
        "timestamp_color": "#999999",
        "separator_color": "#bbbbbb",
        "accent": "#0b93f6",
        "name_color": "#333333",
        "badge_color": "#ff3b30",
        "sms_tag_color": "#4caf50",
        "hint_color": "#999999",
        "dim_color": "#888888",
    },
}

THEME_ORDER = ["midnight", "console", "ocean", "ember", "vapor", "mono", "imessage"]


def get_theme(name: str) -> dict:
    return THEMES.get(name, THEMES["midnight"])
